name: Back Merge

on:
  push:
    branches:
      - master
      - qa

jobs:
  create-pull-request:
    runs-on: [self-hosted, frontend]
    steps:
      - name: ì²´í¬ì•„ì›ƒ
        uses: actions/checkout@v2

      - name: PR ìë™ìƒì„±(Main -> QA)
        if: ${{ github.base_ref == 'main' }}
        id: cpr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "qa"
          github_token: ${{ secrets.SECRET_GH_TOKEN }}
          pr_body: "ğŸ‘‘ **Main -> QA**"
          pr_label: "Automated,BackMerge"
          pr_title: "Main -> QA"

      - name: PR ìë™ìƒì„±(QA -> develop)
        if: ${{ github.base_ref == 'qa' }}
        id: cpr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets.SECRET_GH_TOKEN }}
          pr_body: "ğŸ‘‘ **QA -> Develop**"
          pr_label: "Automated,BackMerge"
          pr_title: "QA -> Develop"

      - name: Safe directoryì„¤ì •
        run: |
          git config --global --add safe.directory /github/workspace

      - name: Auto Merge ì˜µì…˜ ì ìš©
        if: steps.cpr.outputs.pr_number != null
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.SECRET_GH_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pr_number }}
